node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'a8755238-5b01-43ac-8b63-68c75c5ca3c2') {
       def app = docker.build("r7rajkumar/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
